# Generated by Django 3.2.5 on 2021-07-20 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('email', models.EmailField(max_length=225, null=True, unique=True)),
                ('ship_code', models.CharField(max_length=225, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('from_name', models.CharField(blank=True, max_length=225)),
                ('from_address', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('insurance', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='NO', max_length=50)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('in progress', 'IN PROGRESS'), ('shipped', 'SHIPPED'), ('recieved', 'RECIEVED')], default='pending', max_length=250)),
                ('date_order', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=225)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.shipment')),
            ],
        ),
    ]
