# Generated by Django 3.2.5 on 2021-07-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210720_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('recieved', 'RECIEVED'), ('awaiting', 'AWAITING CLEARANCE'), ('in progress', 'IN PROGRESS'), ('in transit', 'IN TRANSIT'), ('shipped', 'SHIPPED'), ('delivered', 'DELIVERED')], default='pending', max_length=250),
        ),
    ]
