# Generated by Django 3.2.5 on 2021-07-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='ship_type',
            field=models.CharField(choices=[('air freight', 'AIR FREIGHT'), ('ocean freight', 'OCEAN FREIGHT'), ('procurement', 'PROCUMENT')], default='procurement', max_length=200),
        ),
    ]
